ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_name  VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS username   VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS is_bot     BOOLEAN     NOT NULL DEFAULT FALSE;
